# - Device Configuration -
devices: devices 

# - Processors -
processors:
- python: # - Add Python Processor
    directory: processors

# - Modules -
modules:
- mqtt-relay: # - Add MQTT Relay module (TLS)
    server: 192.168.1.23
    port: 8883
    qos: 1
    currentInterval: 10000
    sampleInterval: 500
    allowUntrustedCertificates: true
    clientId: J55-411045-persistency
    documentFormat: JSON
    topicPrefix: MTConnect
    topicStructure: Entity
    tls:
      verifyClientCertificate: false
      pem:
        certificateAuthority: C:\Users\Viraj.Dere\Downloads\client-device-certificate\GroupCACertificate.pem
        certificatePath: C:\Users\Viraj.Dere\Downloads\client-device-certificate\certificate.pem
        privateKeyPath: C:\Users\Viraj.Dere\Downloads\client-device-certificate\privateKey.pem

- shdr-adapter: # - Add SHDR Adapter module for Device = PJ and Port = 7878
    deviceKey: J55-411045-persistency   
    hostname: localhost
    port: 7878
    heartbeat: 1000 
    ignoreHeartbeatOnChange: false

# The maximum number of Observations the agent can hold in its buffer
observationBufferSize: 150000

# The maximum number of assets the agent can hold in its buffer
assetBufferSize: 1000

# Sets whether the Agent buffers are durable and retain state after restart
durable: true

# Disables the Agent Device
# enableAgentDevice: false

# Sets the default MTConnect version to output response documents for.
defaultVersion: 2.1
